In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score,classification_report,recall_score
import tensorflow as tf
import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import to_categorical

In [3]:
df=pd.read_csv("Churn_Modelling.csv")

In [4]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [7]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [8]:
df["HasCrCard"].value_counts()

HasCrCard
1    7055
0    2945
Name: count, dtype: int64

In [9]:
x=df.drop(["RowNumber","CustomerId","Surname","Exited"],axis=1)
y=df["Exited"]

In [10]:
x=pd.get_dummies(x,columns=["Geography","Gender"],drop_first=True)

In [11]:
x=x.astype(int)

In [12]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,0,0,0
1,608,41,1,83807,1,0,1,112542,0,1,0
2,502,42,8,159660,3,1,0,113931,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0
4,850,43,2,125510,1,1,1,79084,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,1
9997,709,36,7,0,1,0,1,42085,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0

In [13]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.20, random_state=42)

In [14]:
x_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
9254,686,32,6,0,2,1,1,179093,0,0,1
1561,632,42,4,119624,2,1,1,195978,1,0,1
1670,559,24,3,114739,1,1,0,85891,0,1,1
6087,561,27,9,135637,1,1,0,153080,0,0,0
6669,517,56,9,142147,1,0,0,39488,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
5734,768,54,8,69712,1,1,1,69381,0,0,1
5191,682,58,1,0,1,1,1,706,0,0,0
5390,735,38,1,0,3,0,0,92220,0,0,0
860,667,43,8,190227,1,1,0,97508,0,0,1
7270,697,51,1,147910,1,1,1,53581,1,0,1

In [15]:
scaler=StandardScaler()
x_train_scaler=scaler.fit_transform(x_train)
x_test_scaler=scaler.transform(x_test)

In [16]:
model=Sequential()
model.add(Dense(128,activation="relu",input_dim=11))
model.add(Dropout(0.1))
model.add(Dense(64,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(8,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(1,activation="sigmoid"))

In [17]:
import numpy as np

print(type(x_train_scaler))   # confirms it's a numpy.ndarray
print(x_train_scaler.shape)   # shows rows & columns
print(x_train_scaler[:5])     # shows first 5 rows

<class 'numpy.ndarray'>
(8000, 11)
[[ 0.35649971 -0.6557859   0.34567966 -1.21846978  0.80843615  0.64920267
   0.97481699  1.36767384 -0.57946723 -0.57638802  0.91324755]
 [-0.20389777  0.29493847 -0.3483691   0.69683557  0.80843615  0.64920267
   0.97481699  1.66124779  1.72572313 -0.57638802  0.91324755]
 [-0.96147213 -1.41636539 -0.69539349  0.61862161 -0.91668767  0.64920267
  -1.02583358 -0.25279868 -0.57946723  1.73494238  0.91324755]
 [-0.94071667 -1.13114808  1.38675281  0.95322045 -0.91668767  0.64920267
  -1.02583358  0.91539437 -0.57946723 -0.57638802 -1.09499335]
 [-1.39733684  1.62595257  1.38675281  1.05745236 -0.91668767 -1.54035103
  -1.02583358 -1.05959239 -0.57946723 -0.57638802  0.91324755]]

In [18]:
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=["accuracy"])

In [19]:
history = model.fit(x_train_scaler, y_train,epochs=100,batch_size=8,validation_data=(x_test_scaler, y_test))

Epoch 1/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8284 - loss: 0.4233 - val_accuracy: 0.8530 - val_loss: 0.3560
Epoch 2/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8487 - loss: 0.3681 - val_accuracy: 0.8605 - val_loss: 0.3458
Epoch 3/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8551 - loss: 0.3591 - val_accuracy: 0.8640 - val_loss: 0.3358
Epoch 4/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8579 - loss: 0.3511 - val_accuracy: 0.8560 - val_loss: 0.3510
Epoch 5/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8608 - loss: 0.3474 - val_accuracy: 0.8600 - val_loss: 0.3390
Epoch 6/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8648 - loss: 0.3412 - val_accuracy: 0.8580 - val_loss: 0.3373
Epoch 7/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.8637 - loss: 0.3381 - val_accuracy: 0.8585 - val_loss: 0.3415
Epoch 8/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8656 - loss: 0.3367 - val_accuracy: 0.8565 - val_loss: 0.3436
Epoch 9/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8674 - loss: 0.3336 - val_accuracy: 0.8575 - val_loss: 0.3398
Epoch 10/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8655 - loss: 0.3331 - val_accuracy: 0.8575 - val_loss: 0.3436
Epoch 11/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8673 - loss: 0.3332 - val_accuracy: 0.8595 - val_loss: 0.3415
Epoch 12/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8644 - loss: 0.3296 - val_accuracy: 0.8560 - val_loss: 0.3455
Epoch 13/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8668 - loss: 0.3285 - val_accuracy: 0.8605 - val_loss: 0.3420
Epoch 14/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8677 - loss: 0.3245 - val_accuracy: 0.8570 - val_loss: 0.3507
Epoch 15/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8706 - loss: 0.3206 - val_accuracy: 0.8590 - val_loss: 0.3434
Epoch 16/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8699 - loss: 0.3214 - val_accuracy: 0.8580 - val_loss: 0.3445
Epoch 17/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8706 - loss: 0.3168 - val_accuracy: 0.8560 - val_loss: 0.3439
Epoch 18/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8714 - loss: 0.3143 - val_accuracy: 0.8565 - val_loss: 0.3527
Epoch 19/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8683 - loss: 0.3172 - val_accuracy: 0.8625 - val_loss: 0.3428
Epoch 20/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8719 - loss: 0.3100 - val_accuracy: 0.8510 - val_loss: 0.3543
Epoch 21/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8726 - loss: 0.3106 - val_accuracy: 0.8595 - val_loss: 0.3582
Epoch 22/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8742 - loss: 0.3067 - val_accuracy: 0.8585 - val_loss: 0.3583
Epoch 23/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8735 - loss: 0.3068 - val_accuracy: 0.8590 - val_loss: 0.3584
Epoch 24/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.8766 - loss: 0.3069 - val_accuracy: 0.8585 - val_loss: 0.3631
Epoch 25/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8721 - loss: 0.3025 - val_accuracy: 0.8595 - val_loss: 0.3569
Epoch 26/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8755 - loss: 0.2997 - val_accuracy: 0.8555 - val_loss: 0.3627
Epoch 27/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8765 - loss: 0.3007 - val_accuracy: 0.8560 - val_loss: 0.3578
Epoch 28/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8788 - loss: 0.2973 - val_accuracy: 0.8580 - val_loss: 0.3643
Epoch 29/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8752 - loss: 0.2985 - val_accuracy: 0.8515 - val_loss: 0.3612
Epoch 30/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8769 - loss: 0.2934 - val_accuracy: 0.8555 - val_loss: 0.3632
Epoch 31/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8788 - loss: 0.2944 - val_accuracy: 0.8555 - val_loss: 0.3670
Epoch 32/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8786 - loss: 0.2910 - val_accuracy: 0.8590 - val_loss: 0.3720
Epoch 33/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8777 - loss: 0.2907 - val_accuracy: 0.8540 - val_loss: 0.3666
Epoch 34/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8832 - loss: 0.2880 - val_accuracy: 0.8580 - val_loss: 0.3628
Epoch 35/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8813 - loss: 0.2853 - val_accuracy: 0.8595 - val_loss: 0.3708
Epoch 36/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8815 - loss: 0.2874 - val_accuracy: 0.8620 - val_loss: 0.3689
Epoch 37/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8824 - loss: 0.2815 - val_accuracy: 0.8600 - val_loss: 0.3675
Epoch 38/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8798 - loss: 0.2802 - val_accuracy: 0.8605 - val_loss: 0.3833
Epoch 39/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8808 - loss: 0.2825 - val_accuracy: 0.8565 - val_loss: 0.3830
Epoch 40/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8821 - loss: 0.2803 - val_accuracy: 0.8580 - val_loss: 0.3768
Epoch 41/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8836 - loss: 0.2789 - val_accuracy: 0.8595 - val_loss: 0.3743
Epoch 42/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8838 - loss: 0.2771 - val_accuracy: 0.8600 - val_loss: 0.3787
Epoch 43/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8841 - loss: 0.2756 - val_accuracy: 0.8575 - val_loss: 0.3837
Epoch 44/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8831 - loss: 0.2719 - val_accuracy: 0.8525 - val_loss: 0.3937
Epoch 45/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8846 - loss: 0.2726 - val_accuracy: 0.8565 - val_loss: 0.3836
Epoch 46/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8846 - loss: 0.2742 - val_accuracy: 0.8550 - val_loss: 0.4007
Epoch 47/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8865 - loss: 0.2673 - val_accuracy: 0.8510 - val_loss: 0.4033
Epoch 48/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8870 - loss: 0.2658 - val_accuracy: 0.8530 - val_loss: 0.4049
Epoch 49/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8850 - loss: 0.2708 - val_accuracy: 0.8545 - val_loss: 0.4012
Epoch 50/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8882 - loss: 0.2676 - val_accuracy: 0.8585 - val_loss: 0.3883
Epoch 51/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8873 - loss: 0.2647 - val_accuracy: 0.8565 - val_loss: 0.4004
Epoch 52/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8884 - loss: 0.2642 - val_accuracy: 0.8540 - val_loss: 0.4084
Epoch 53/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8900 - loss: 0.2642 - val_accuracy: 0.8530 - val_loss: 0.4067
Epoch 54/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8894 - loss: 0.2622 - val_accuracy: 0.8550 - val_loss: 0.4119
Epoch 55/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8891 - loss: 0.2624 - val_accuracy: 0.8565 - val_loss: 0.4095
Epoch 56/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8874 - loss: 0.2603 - val_accuracy: 0.8560 - val_loss: 0.4127
Epoch 57/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8906 - loss: 0.2597 - val_accuracy: 0.8575 - val_loss: 0.4036
Epoch 58/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8923 - loss: 0.2575 - val_accuracy: 0.8555 - val_loss: 0.4096
Epoch 59/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8957 - loss: 0.2536 - val_accuracy: 0.8590 - val_loss: 0.3987
Epoch 60/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8925 - loss: 0.2528 - val_accuracy: 0.8575 - val_loss: 0.4183
Epoch 61/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8917 - loss: 0.2580 - val_accuracy: 0.8490 - val_loss: 0.4238
Epoch 62/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8929 - loss: 0.2474 - val_accuracy: 0.8550 - val_loss: 0.4234
Epoch 63/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8929 - loss: 0.2503 - val_accuracy: 0.8535 - val_loss: 0.4194
Epoch 64/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8950 - loss: 0.2507 - val_accuracy: 0.8540 - val_loss: 0.4286
Epoch 65/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8923 - loss: 0.2532 - val_accuracy: 0.8555 - val_loss: 0.4217
Epoch 66/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8941 - loss: 0.2469 - val_accuracy: 0.8560 - val_loss: 0.4225
Epoch 67/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8938 - loss: 0.2455 - val_accuracy: 0.8535 - val_loss: 0.4295
Epoch 68/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8965 - loss: 0.2484 - val_accuracy: 0.8530 - val_loss: 0.4474
Epoch 69/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8954 - loss: 0.2463 - val_accuracy: 0.8600 - val_loss: 0.4415
Epoch 70/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8951 - loss: 0.2435 - val_accuracy: 0.8510 - val_loss: 0.4437
Epoch 71/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8942 - loss: 0.2466 - val_accuracy: 0.8550 - val_loss: 0.4257
Epoch 72/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8916 - loss: 0.2449 - val_accuracy: 0.8535 - val_loss: 0.4290
Epoch 73/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8925 - loss: 0.2445 - val_accuracy: 0.8435 - val_loss: 0.4387
Epoch 74/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8947 - loss: 0.2441 - val_accuracy: 0.8485 - val_loss: 0.4407
Epoch 75/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8936 - loss: 0.2465 - val_accuracy: 0.8560 - val_loss: 0.4305
Epoch 76/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8953 - loss: 0.2409 - val_accuracy: 0.8520 - val_loss: 0.4465
Epoch 77/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8942 - loss: 0.2439 - val_accuracy: 0.8575 - val_loss: 0.4475
Epoch 78/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8926 - loss: 0.2403 - val_accuracy: 0.8595 - val_loss: 0.4344
Epoch 79/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8955 - loss: 0.2353 - val_accuracy: 0.8565 - val_loss: 0.4413
Epoch 80/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8969 - loss: 0.2412 - val_accuracy: 0.8565 - val_loss: 0.4342
Epoch 81/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8985 - loss: 0.2326 - val_accuracy: 0.8550 - val_loss: 0.4450
Epoch 82/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8926 - loss: 0.2377 - val_accuracy: 0.8520 - val_loss: 0.4337
Epoch 83/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8967 - loss: 0.2301 - val_accuracy: 0.8520 - val_loss: 0.4678
Epoch 84/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9021 - loss: 0.2284 - val_accuracy: 0.8520 - val_loss: 0.4733
Epoch 85/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9010 - loss: 0.2310 - val_accuracy: 0.8555 - val_loss: 0.4506
Epoch 86/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8971 - loss: 0.2312 - val_accuracy: 0.8500 - val_loss: 0.4660
Epoch 87/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8978 - loss: 0.2316 - val_accuracy: 0.8505 - val_loss: 0.4542
Epoch 88/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8997 - loss: 0.2284 - val_accuracy: 0.8530 - val_loss: 0.4614
Epoch 89/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8997 - loss: 0.2317 - val_accuracy: 0.8445 - val_loss: 0.4525
Epoch 90/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8971 - loss: 0.2340 - val_accuracy: 0.8535 - val_loss: 0.4552
Epoch 91/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9007 - loss: 0.2234 - val_accuracy: 0.8510 - val_loss: 0.4668
Epoch 92/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8985 - loss: 0.2295 - val_accuracy: 0.8495 - val_loss: 0.4599
Epoch 93/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8959 - loss: 0.2346 - val_accuracy: 0.8540 - val_loss: 0.4702
Epoch 94/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8995 - loss: 0.2321 - val_accuracy: 0.8525 - val_loss: 0.4665
Epoch 95/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9014 - loss: 0.2236 - val_accuracy: 0.8515 - val_loss: 0.4677
Epoch 96/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8995 - loss: 0.2273 - val_accuracy: 0.8515 - val_loss: 0.4828
Epoch 97/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8995 - loss: 0.2254 - val_accuracy: 0.8530 - val_loss: 0.4613
Epoch 98/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9031 - loss: 0.2268 - val_accuracy: 0.8540 - val_loss: 0.4687
Epoch 99/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8997 - loss: 0.2272 - val_accuracy: 0.8505 - val_loss: 0.4625
Epoch 100/100
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8989 - loss: 0.2324 - val_accuracy: 0.8540 - val_loss: 0.4688

In [20]:
y_pred=model.predict(x_test_scaler)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [21]:
y_pred=np.where(y_pred>0.5,1,0)

In [22]:
accuracy_score(y_test,y_pred)

0.854

In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1607
           1       0.69      0.47      0.56       393

    accuracy                           0.85      2000
   macro avg       0.78      0.71      0.74      2000
weighted avg       0.84      0.85      0.84      2000

In [24]:
import joblib
model.save("model.keras")

In [25]:
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']